// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Mhill888
//@version=6
indicator("Volume Pressure", overlay=false)


//--- variables

lenSmooth = input.int(14, "Smoothing length", minval=1)
lenZ      = input.int(200, "Lookback length", minval=20)
useLogVol = input.bool(true, "Use log volume")
showSignals   = input.bool(false, "Show direction markers")
showZero   = input.bool(true, "Show zero line")
showBands   = input.bool(true, "Show bands normal")
showBandsH   = input.bool(true, "Show bands high volatility")

//--- maths

// wick ratio - body range divided by total range
wickR = (close - open) / (high - low)

// volume weighting
logV = math.log(volume)

// candle range * volume
volRange = (wickR * logV)

// cumulative value
var float volRangeSum = na
volRangeSum := na(volRangeSum) ? volRange : (volRangeSum + volRange)

// exponential average of cumulative value
sm = ta.ema(volRangeSum, lenSmooth)

// simple average of exponential average of cumulative value
mean  = ta.sma(sm, lenZ)
// standard deviation of exponential average of cumulative value
stdev = ta.stdev(sm, lenZ)
// if stdev is 0 z is 0, else z is ->
// exponential average of cumulative value - simple average of exponential average of cumulative value
// divided by the standard deviation

z     = stdev == 0 ? 0 : (sm - mean) / stdev

// candles
zOpen  = 0
zClose = z
zHigh  = math.max(zOpen, zClose)
zLow   = math.min(zOpen, zClose)

bull = zClose >= zClose[1] and zClose >= 0
fadingBull = zClose < zClose[1] and zClose >= 0
bear = zClose < zClose[1] and zClose <0



//-----
// plot
//-----
plotcandle(
     open=zOpen, high=zHigh, low=zLow, close=zClose,
     title="Volume Candles",
     color=bull ? color.new(color.teal, 0) : bear ? color.red : fadingBull ? color.new(color.teal, 50) : color.new(color.red, 50),
     wickcolor=color.new(color.gray, 40),
     bordercolor=bull ? color.new(color.teal, 0) : bear ? color.red : fadingBull ?  color.new(color.teal, 50) : color.new(color.red, 50)
)